### ISSUE TITLE
Missing cef_library_loader.h

### ISSUE THREAD

**Issue by fbrier** [cefsharp/cef-binary#99] opened 2021-08-16 15:06 UTC
Performing a package restore using 92.0.25, and building results in
```
fatal error C1083: Cannot open include file: 'cef_library_loader.h': No such file or directory
```
The file does not appear to be in .\packages\cef.sdk.92.0.25\CEF\include\wrapper. It does appear to have been in [master](https://bitbucket.org/chromiumembedded/cef/src/master/include/wrapper/) since last year. The other headers are in the wrapper folder, why not this one? Thank you.

**Comment by amaitland** [comment] 2021-08-16 20:31
> Performing a package restore using 92.0.25, and building results in

What project are you restoring exactly? CefSharp builds are passing as expected. 

The files are included recursively 

https://github.com/cefsharp/cef-binary/blob/master/NuGet/cef.sdk.nuspec#L22

You can build locally to debug.

**Comment by fbrier** [comment] 2021-08-17 00:59
The package is restoring correctly. I don't think this is a bug, just trying to understand why a file in the source tree is not in the Nuget package/distribution. The exact line in the packages.config is:
```xml
  <package id="cef.sdk" version="92.0.25"/>
```
It is just that the file is not there. So I [downloaded the standard distribution](https://cef-builds.spotifycdn.com/index.html) for the current stable build, unpacked it, and it isn't there either. The [file does appear to be in master](https://github.com/chromiumembedded/cef/blob/master/include/wrapper/cef_library_loader.h). Thoughts?

**Comment by amaitland** [comment] 2021-08-17 01:13
> The exact line in the packages.config is:

What project are you using? CefSharp or something else?

> It is just that the file is not there. So I downloaded the standard distribution for the current stable build, unpacked it, and it isn't there either.

Thanks for checking,  I'm going to close this issue as it's not a bug.

> The file does appear to be in master. Thoughts?

I don't know. I don't believe it's used on Windows, so maybe it's only in the linux/mac packages. 

CEF has it's own forum at https://magpcss.org/ceforum/index.php you'll have better luck ask there.

**Closed by amaitland** 2021-08-17 01:13 UTC
